# Code generated by kickr; DO NOT EDIT.

import "scripts/just/clean.just"
import? "scripts/just/custom.just"
import "scripts/just/lint.just"

# modules/git module commands.
mod modules-git "modules/git/Justfile"

# list available recipes.
default:
    @just --list
