billing_user: ENC[AES256_GCM,data:rT8xTEFSEw==,iv:rhcBQ9ZVpESs2EvbGi2YkeYJcAze5teU4NBUrV3ohNk=,tag:6Ufnvnawd1Bmb7A3okWBWQ==,type:str]
codecov_token: ENC[AES256_GCM,data:YGzLW5u2Wle25X1Vd9SlQDdxz1Q9ZMcmm4+OsjirR+eh0wg0,iv:JKRTrlso+x6wCBKynJMAVCHWXO5gjKV5UGlpL8fciv4=,tag:S6mPk6ybCN7Vtdpapl4s+Q==,type:str]
github_com_token: ENC[AES256_GCM,data:BBS3Wr7ajMyy4ulNaDUOeP0q/wzwjs++nhV9R+J51twZrMCBIi4seHQyJvN8L9eaYuSId4agXIOa6AcEz7/u4HZ7CKCGmwwNhf6Uq6SxqmVyyA5+vhuPjEXgdUvZ,iv:OaZZ3gsTs8bMvLQ9hHnvMnWwXv1akgFO6wnd2fSDX1w=,tag:v5ADQHCyWYFjIkrjg+/leQ==,type:str]
github_mirror_token: ENC[AES256_GCM,data:0muEdaBum4bxA653O2aROiwKo1ThlhJx/a9rn/sYnJ5dDnBZn0u+B9i2dy3BwEp4hPP7Y8DoSPguqdVm4M/24zD5lMDCfVyQC6C87SKTJ3MzbRwchuACKgX1tLC1,iv:OFQAgyGZCdpsOY9H5nCKnTO5jck3bh0o5L/iHNpTeCw=,tag:nJACCzE9RbW5EY+8N2XteQ==,type:str]
support_user: ENC[AES256_GCM,data:paPo3luXOQ==,iv:2ibrhGbWfEf2Hh66E5+Vp3cBbFmSL8ryPRIQwzX/hYM=,tag:Vzlhyh8kGwZjvbpbAeQZsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMXBBa1lGY3NXM0FlSEV2
            WXNPMFNtbVFZcHdIZnVkQnpWN0VzcFJQZ3ljCmNKRFZUa1hSL3dNNTVOSGduR1VO
            QXkzYkVCdHQxUTNWYkYya1g4WjdZODAKLS0tIHd0TG5vTmNSd3VUTDdPaWZpT2xN
            dkdGZlNoQmdrNVFRc1BTOUtnNExYZFUKCX/VUrDpm8XBYuNTNcWPK6W5MJQ8pTwg
            LD6R5vSDYRLkxRT5wwsu6spELw6S3XE2LAMd1pTWYiEttZKCPBriEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ug8mc4498j6c7a0ymtptu9gxecsk369zn24gx9q5gklrr5w74fjqkf5ug4
    lastmodified: "2026-08-07T16:46:20Z"
    mac: ENC[AES256_GCM,data:05663UMRMu0RCxkNqoOpWpRMb0Df+0ZYcPFg6TPnSR+P4XNQUCk33EviJzx5bX9dQYNHR5GFYw1WW3gqo3AaEJNTTvbGfcwzUNlp7+nEQfzlCQQUNdCqCTd4iC5VzaIl02VispYqFSZO2uuDgjVoAdp5kvhkIjSwkM7zV3L/45Y=,iv:tx2aaUBZL3pQI44ncqqd4H5yLmY5szK+vOgmRA7hOD0=,tag:6AEr/TTrec1xKQ+Hg519hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
