github_terraform_token: ENC[AES256_GCM,data:i96mCbDQpZg8vUWebdbmdDcRLqp18LM+MU4QlJx/DHNNlVk1g41kzeD9dGqe9YMPdRzl3+VgnL8k1EyzFTf9LMoNFbAj/qC91tihAkeykgDlLSH10/B8LELuOYe9,iv:yWLKE+3yX5UPlVYFCAWxKhjBdCC/sNZU0kkVEm4QNGU=,tag:MgzxTtCtPGJpQ8S1XUj3xA==,type:str]
gitlab_terraform_token: ENC[AES256_GCM,data:Za+jPA5PmfoudF7zKRWKP9Z3uNhxTa5U7jrFFjppKr6CmiaqnhGljAP01ld+Fp5Zbtnprj0I+SGbnKvc/Eo=,iv:uqeJ7YWr3ebwoMUshs0Uuz+FfNYyPE17bD7HbE4UIxE=,tag:Kc8GqMA86JresCkVyl36XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRXFrNCtVVFEwYjhoTFI4
            NnNGRXIrMHNkQzRzL1pWakk4MWZpN3Jwc1VzClJvVlpsK1pYR1RERXBNdjFYZHZN
            YXMxNXpOT1UvZldmRzAzbUZCOUgvK1EKLS0tICtUMkZTSkc2OEM4UUt2NGhEZEx6
            dnl5YUJBVnc3ZzRoVUpQbWZXK2hJeTgKoff/Td6KMCFhdhwmwAIW97IPSvT7recr
            FerV4Y8imXMPgC5FFzl2CaKtCnuS/1IYsnoejWL+BA6pB6CtUatVtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ug8mc4498j6c7a0ymtptu9gxecsk369zn24gx9q5gklrr5w74fjqkf5ug4
    lastmodified: "2026-09-06T18:54:10Z"
    mac: ENC[AES256_GCM,data:Mdgsiri/Va/qZQtpBcLw4V0eLbrlSIIZ9AZzXKkDDqqrIWGgTCXWiDk6z7ktI1YSG18kvCccswLH5zByxEYBbA42xOgjM4eqCcK9aMfKjbYrN9OPzoUkmVZOh3kOcUL6Rl14TPNfvHW0iosbSt3I0z1ZvaZq6TFeBWXhqcI79OQ=,iv:sUdglahtJmSru8O5wXilVfrOLdrhcF49XbBq8MhxDGk=,tag:f/y3xirFaRqJKUF48D9XOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
