github_terraform_token: ENC[AES256_GCM,data:i96mCbDQpZg8vUWebdbmdDcRLqp18LM+MU4QlJx/DHNNlVk1g41kzeD9dGqe9YMPdRzl3+VgnL8k1EyzFTf9LMoNFbAj/qC91tihAkeykgDlLSH10/B8LELuOYe9,iv:yWLKE+3yX5UPlVYFCAWxKhjBdCC/sNZU0kkVEm4QNGU=,tag:MgzxTtCtPGJpQ8S1XUj3xA==,type:str]
gitlab_terraform_token: ENC[AES256_GCM,data:EUZofxCDAJsDSsp18G0+ZMnjIsgMAg2Jb5o4zM+zwr9atgO3UFu1W72RjIds1GpAxq4UmbhA/+3V,iv:zClPxlylnhfNE8OwtDjvY6fW8sBm+H4aYiQ3vrwZ/AA=,tag:lEjVV+qTIoCjufRmK6mQqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRXFrNCtVVFEwYjhoTFI4
            NnNGRXIrMHNkQzRzL1pWakk4MWZpN3Jwc1VzClJvVlpsK1pYR1RERXBNdjFYZHZN
            YXMxNXpOT1UvZldmRzAzbUZCOUgvK1EKLS0tICtUMkZTSkc2OEM4UUt2NGhEZEx6
            dnl5YUJBVnc3ZzRoVUpQbWZXK2hJeTgKoff/Td6KMCFhdhwmwAIW97IPSvT7recr
            FerV4Y8imXMPgC5FFzl2CaKtCnuS/1IYsnoejWL+BA6pB6CtUatVtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ug8mc4498j6c7a0ymtptu9gxecsk369zn24gx9q5gklrr5w74fjqkf5ug4
    lastmodified: "2026-08-07T16:33:05Z"
    mac: ENC[AES256_GCM,data:ChCj1SYjsZ6wzk0UlZtDL/GldzkummsPaKHSWLVzVkSijOFAratb7lD76yTrGINWV7BS1W+kwUo6DDplaWFlYN/vdGuyDljnbGB3TwLraWpsUUAvSpwvF+dPQ+OlnzztS5gMWt16EKhvwBUF//r+BdV6EcQNd/Iadm1DbPQI0UE=,iv:SwlLkVeWvKV7UWCGH0965wqkI4pam4a38xjdynzlKZI=,tag:8P5RO6oRfQS9MeiPPUeLQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
